Дописать e2e тест на cypress для удаления задачи в подпроекте ’09-ts-todo-mvc-react-with-tests’
step-ponomarev/js-101-2020 pull request #2
Opened 2021-03-22 17:43 UTC by step-ponomarev

2021-04-04 11:51 UTC, DmitryMakhnev requested changes

2021-04-04 11:51 UTC, DmitryMakhnev commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/manage-todos.spec.ts
> +      cy.get(`[data-test-id=todo-item__text-input][value="${itemText}"] + [data-test-id=todo-item__remove-action]`).click({force: true});
Несколько моментов:
- Нужно описать отдельный тест на удаление, т.к. в случае падения данного теста очень не понятно что конкретно сломалось: добавление или удаление?
- Нужно так же сделать intercepter на запрос удаления, иначе как сейчас у вас проверился только клиентский код, и если он перестанет отправлять на сервер запрос, программа будет работать некорректно, а тест останется зелёным

2021-04-04 11:53 UTC, DmitryMakhnev commented
Так же, если вы используйте `npm` для установки зависимостей, пожалуйста, добавьте `package.lock` в `.gitignore`

2021-04-10 16:39 UTC, step-ponomarev commented
Поправил

2021-04-11 16:58 UTC, DmitryMakhnev approved these changes

2021-04-11 16:58 UTC, DmitryMakhnev commented on 09-ts-todo-mvc-react-with-tests/tests/e2e/todos-page/todo-remove.spec.ts
> +function authorize() {
Не стоит разводить копипасту. Общий код для тестов можно так же выносить в отдельные модули

2021-04-29 05:50 UTC, merged